@startuml
participant sender
participant receiver
collections contract
collections store
collections events

sender->contract ++ #gold: bridgeAsset

contract->events : bridgeMessage
contract->store : updateState
return success

receiver<--events: notify

receiver->contract ++ #green: claimAsset

contract->events: claimMessage
contract->store: updateState
return success

events-->sender: notify
@enduml
